# Generated by Django 5.1.3 on 2024-11-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0003_remove_employee_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.CharField(default="Not Assigned", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="salary",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="employee",
            name="date_joined",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(default="N/A", max_length=15),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(max_length=100),
        ),
    ]
