# Generated by Django 5.1.3 on 2024-11-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0004_employee_department_employee_salary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="hourly_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
