# Generated by Django 5.1.3 on 2024-11-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0008_leaverequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Software Engineer", "Software Engineer"),
                    ("Developer", "Developer"),
                    ("Manager", "Manager"),
                    ("HR", "HR"),
                ],
                default="Developer",
                max_length=20,
            ),
        ),
    ]
