# Generated by Django 5.1.3 on 2024-11-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("apis", "0015_rename_customuser_user"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="CustomUser",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="user",
        ),
        migrations.AlterField(
            model_name="employee",
            name="date_joined",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Software Engineer", "Software Engineer"),
                    ("Manager", "Manager"),
                    ("Hr", "HR"),
                    ("Developer", "Developer"),
                ],
                default="Developer",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=50,
                null=True,
            ),
        ),
    ]
