# Generated by Django 5.1.3 on 2024-11-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0016_rename_user_customuser_remove_employee_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
