# Generated by Django 5.1.3 on 2024-12-03 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0022_alter_payroll_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payroll",
            name="scheduled_date",
        ),
        migrations.AddField(
            model_name="payroll",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Completed", "Completed")],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Software Engineer", "Software Engineer"),
                    ("Manager", "Manager"),
                    ("HR", "HR"),
                    ("Developer", "Developer"),
                ],
                default="Developer",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="apis.employee"
            ),
        ),
    ]
