# Generated by Django 5.1.3 on 2024-12-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0024_customuser_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
