# Generated by Django 5.1.3 on 2024-12-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0025_customuser_hourly_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="hourly_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
