# Generated by Django 5.1.3 on 2024-12-11 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0026_alter_customuser_hourly_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payroll",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="payroll",
            name="payment_date",
        ),
        migrations.RemoveField(
            model_name="payroll",
            name="status",
        ),
        migrations.AddField(
            model_name="payroll",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payroll",
            name="days_worked",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payroll",
            name="monthly_salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="total_working_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
