# Generated by Django 5.1.3 on 2024-12-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0027_remove_payroll_amount_remove_payroll_payment_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="payment_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
